import { ThemeProvider } from "@mui/system"
import theme from "./theme"

import "./globals.css"

export const metadata = {
  title: "Kaze Comics",
  description: "Generated by shayy",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  )
}
